'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CalendarDays,MapPin,Clock} from 'lucide-react';
import {Frame,Eyebrow,ShareButton} from './wedding';
import {useWeddingEvent} from './event-context';
import {displayDate,displayTime,displayTimezone,type WeddingEvent} from '@/lib/event-types';
import {guestDetails} from '@/lib/guest-details';
import {DressColours,GuestContacts} from './guest-information';
import {VenuePhotograph} from './venue-photograph';

function saveFile(text:string,name:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function eventInstant(e:WeddingEvent){if(!e.date||!e.timezone)return null;const basic=Date.parse(e.date+'T'+e.time+':00Z');let utc=basic;for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:e.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(utc));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const local=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);utc+=basic-local;}return utc;}
export function CalendarButton({event}:{event:WeddingEvent}){if(!event.date||!event.timezone)return null;const save=()=>{const utc=eventInstant(event);if(!utc)return;const stamp=(d:number)=>new Date(d).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const data=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Frederick and Veronica//Wedding//EN','BEGIN:VEVENT','UID:frederick-veronica-wedding@wedding',`DTSTAMP:${stamp(Date.now())}`,`DTSTART:${stamp(utc)}`,'SUMMARY:Frederick & Veronica — Wedding',`LOCATION:${esc([event.venue,event.address].filter(Boolean).join(', '))}`,'DESCRIPTION:Celebrate the wedding of Frederick Amokohene and Veronica Owusu.','END:VEVENT','END:VCALENDAR'].join('\r\n');saveFile(data,'Frederick-Veronica-Wedding.ics','text/calendar')};return <button className="button button-burgundy" onClick={save}><CalendarDays size={18}/> Add to calendar</button>}
export function Countdown({event}:{event:WeddingEvent}){const [now,setNow]=useState<number|null>(null);useEffect(()=>{setNow(Date.now());const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const target=eventInstant(event);if(!target||!now||target<=now)return null;const d=target-now;return <div className="countdown" aria-label="Countdown to the wedding">{[[Math.floor(d/86400000),'DAYS'],[Math.floor(d/3600000)%24,'HOURS'],[Math.floor(d/60000)%60,'MINUTES'],[Math.floor(d/1000)%60,'SECONDS']].map(([n,l])=><div key={l}><strong>{String(n).padStart(2,'0')}</strong><span>{l}</span></div>)}</div>}
export function EventDetails({compact=false}:{compact?:boolean}){const event=useWeddingEvent();return <section className={`event-section ${compact?'compact':''}`} id="wedding-details"><div className="event-intro"><Eyebrow>THE DAY WE SAY “I DO”</Eyebrow><h2>Save a place<br/><i>in your heart.</i></h2><p>A celebration of Frederick Amokohene<br/>and Veronica Owusu.</p><Countdown event={event}/></div><div className="event-invitation"><span className="invitation-monogram">F<span>&</span>V</span><h3>You are warmly invited</h3><div className="invitation-facts"><div><CalendarDays/><span><b>The date</b>{displayDate(event.date)}</span></div><div><Clock/><span><b>The ceremony</b>{displayTime(event.time)}{event.timezone&&<small>{displayTimezone(event.timezone)}</small>}</span></div><div><MapPin/><span><b>The venue</b>{event.venue||'Venue details to follow'}{event.address&&<small>{event.address}</small>}</span></div></div>{event.note&&<p className="event-note">{event.note}</p>}<div className="invitation-actions"><CalendarButton event={event}/>{event.venue&&<a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([event.venue,event.address].filter(Boolean).join(', '))}`} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={17}/></a>}{!event.date&&<p className="event-note">Our ceremony begins at noon. The confirmed date and venue will appear here as soon as they are added.</p>}</div></div></section>}
export function GuestGuide({embedded=false}:{embedded?:boolean}){const e=useWeddingEvent();return <><section className="guest-guide"><div className="guide-intro"><Eyebrow>A LITTLE HELP BEFORE THE DAY</Eyebrow><h2>For our<br/><i>favourite people.</i></h2><p className="rsvp-deadline">Please RSVP by <strong>{displayDate(guestDetails.rsvpDeadline)}</strong>.</p><a href={embedded?'#rsvp':'/rsvp'} className="button button-burgundy">Respond to your invitation <ArrowUpRight size={18}/></a><div className="dress-guidance"><h3>What to wear</h3><p>{e.dressCode||guestDetails.dressCode}</p><DressColours/></div></div><div className="guide-questions">{[{q:'Will there be a reception?',a:guestDetails.afterCeremony},{q:'When and how do I RSVP?',a:<>Please respond by <strong>{displayDate(guestDetails.rsvpDeadline)}</strong> using our <a href={embedded?'#rsvp':'/rsvp'}>RSVP form</a>. Include everyone in your party, including children, and share any dietary requirements or access needs. Your response is saved privately for the organizer.</>},{q:'What time does the ceremony begin?',a:<>The ceremony begins at <strong>{e.time==='12:00'?'12:00 noon':displayTime(e.time)}</strong> ({displayTimezone(e.timezone)}). Please allow time to arrive and settle in beforehand.</>},{q:'Where is the wedding taking place?',a:<>{e.venue}, {e.address}. Use <a href={embedded?'#venue':'#wedding-details'}>venue and directions</a> to plan your journey.</>},{q:'Are children welcome?',a:guestDetails.children},{q:'What if I have access needs?',a:<>{guestDetails.accessibility} Find their <a href="#guest-contacts">contact details below</a>.</>},{q:'Is parking available?',a:guestDetails.parking},{q:'What should I expect from the weather?',a:guestDetails.weather},{q:'How can I change my RSVP?',a:<>Contact <a href="#guest-contacts">Ibrahim or Gloria, or email our guest enquiry address</a>, and quote the response reference shown after you submit. Your reference is also in the downloadable confirmation.</>},{q:'Can I download or save the photographs?',a:<>Yes. The <a href="/gallery">gallery</a> includes a full-screen slideshow, individual and collection downloads, and favourites saved on your device.</>}].map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section><GuestContacts/></>}
export function Celebration(){const e=useWeddingEvent();return <Frame page="celebration"><section className="day-header"><Eyebrow>EVERYTHING YOU NEED FOR OUR DAY</Eyebrow><h1>Be here for<br/><i>the beautiful beginning.</i></h1><p>The wedding of Frederick Amokohene & Veronica Owusu</p></section><EventDetails/><section className="celebration-venue" id="venue" aria-label="Our wedding venue"><Eyebrow>THE PLACE WE SAY “I DO”</Eyebrow><VenuePhotograph venue={e.venue} address={e.address}/><a className="text-link" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([e.venue,e.address].filter(Boolean).join(', '))}`} target="_blank" rel="noopener noreferrer">Find your way to us <ArrowUpRight size={18}/></a></section><section className="day-plan"><div><Eyebrow>THE MOMENT THAT MATTERS</Eyebrow><h2>Our day,<br/><i>together.</i></h2></div><div className="ceremony-timeline"><span className="timeline-time">{displayTime(e.time)}</span><div><span className="timeline-dot"/><h3>The wedding ceremony</h3><p>Join Frederick and Veronica as they begin their next chapter.</p><p>{guestDetails.afterCeremony}</p><span className="venue-inline"><MapPin size={16}/>{e.venue||'Venue to be confirmed'}</span></div></div></section><GuestGuide/><section className="day-share"><h2>Good company.<br/><i>A very good day.</i></h2><ShareButton/></section></Frame>}

export {RSVP} from './rsvp/form';
