'use client';
import {useState} from 'react';
import {Phone,MessageCircle,Mail,Copy,Check,Heart} from 'lucide-react';
import {guestDetails} from '@/lib/guest-details';

export function DressColours(){return <div className="dress-colours" aria-label="Optional wedding colours"><span><i style={{background:'#13634b'}}/>Emerald green</span><span><i style={{background:'#b56143'}}/>Terracotta</span><span><i style={{background:'#d7c2a2'}}/>Sand</span></div>}

export function GuestContacts(){
 const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
 async function copyGiftEmail(){try{await navigator.clipboard.writeText(guestDetails.giftEmail);setCopied(true);setCopyError(false);setTimeout(()=>setCopied(false),3000)}catch{setCopyError(true)}}
 return <section className="guest-contacts" id="guest-contacts" aria-labelledby="contacts-heading"><div className="guest-contact-main"><span className="eyebrow">A HELPING HAND</span><h2 id="contacts-heading">Questions before<br/><i>the day?</i></h2><p>For guest enquiries, RSVP changes, or help arranging access needs, please get in touch.</p><div className="contact-people">{guestDetails.contacts.map(contact=><article key={contact.name}><h3>{contact.name}</h3><a className="contact-number" href={`tel:${contact.tel}`}>{contact.phone}</a><div className="contact-actions"><a href={`tel:${contact.tel}`}><Phone size={17}/>Call {'whatsapp' in contact?'Ibrahim':'Gloria'}</a>{'whatsapp' in contact&&<a href={contact.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>WhatsApp</a>}</div></article>)}</div><div className="enquiry-email"><span>Guest enquiries</span><a href={`mailto:${guestDetails.enquiryEmail}`}><Mail size={18}/>{guestDetails.enquiryEmail}</a></div></div><aside className="gift-details" aria-labelledby="gifts-heading"><Heart size={27}/><span className="eyebrow">WITH LOVE & THANKS</span><h3 id="gifts-heading">A thoughtful gift.</h3><p>If you would like to send a gift by Interac e-Transfer, please use:</p><span className="gift-email-label">INTERAC GIFTS ONLY</span><strong className="gift-email">{guestDetails.giftEmail}</strong><button className="text-link" onClick={copyGiftEmail}>{copied?'Gift address copied':'Copy Interac address'}{copied?<Check size={17}/>:<Copy size={17}/>}</button><p className="gift-copy-status" role="status">{copyError?'Please select and copy the gift address above.':copied?'Ready to paste into your banking app.':''}</p><p className="gift-enquiry-note">For questions about the day, use the guest enquiry contacts.</p></aside></section>
}
