'use client';

import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, ChevronLeft, ChevronRight, Heart, Play, Pause, X, Menu, Download, Check, Share2, CalendarDays, MapPin, PenLine, LoaderCircle, BookOpen, Images } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose, DialogTrigger } from '@/components/ui/dialog';
import { Toaster, toast } from 'sonner';

export const photos = [
 {id:'IMG_5392',title:'A lifetime of us',collection:'Together',alt:'Frederick in a cream suit beside Veronica in a rust satin dress, standing together outdoors'},
 {id:'IMG_5386',title:'In your company',collection:'Together',alt:'Frederick and Veronica smiling together beneath the trees'},
 {id:'IMG_5389',title:'The quiet promises',collection:'Together',alt:'Frederick and Veronica looking down together in a tender portrait'},
 {id:'IMG_5390',title:'Just the two of us',collection:'Together',alt:'A black and white portrait of Frederick and Veronica sharing a quiet moment'},
 {id:'IMG_5089',title:'Beautifully, together',collection:'Tradition',alt:'Veronica in colourful traditional clothing standing beside Frederick outdoors'},
 {id:'IMG_5090',title:'Colours of our love',collection:'Tradition',alt:'Frederick and Veronica holding hands in their traditional outfits'},
 {id:'IMG_5132',title:'A glance, a smile',collection:'Tradition',alt:'Veronica seated and smiling up at Frederick as they hold hands'},
 {id:'IMG_5138',title:'Side by side',collection:'Tradition',alt:'Frederick standing beside seated Veronica in coordinated traditional clothing'},
];
const links=[['home','Home'],['our-story','Our story'],['the-day','The day'],['venue','Venue & directions'],['gallery','Gallery'],['guestbook','Guestbook']];
const mobileLinks=[...links,['rsvp','RSVP']];
const sectionHref=(anchor:string,page:string)=>`${page==='home'?'':'/'}#${anchor}`;
const src=(id:string,small=false)=>`/photos/${id}${small?'-small':''}.webp`;

function Header({page}:{page:string}){
 const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const [activeAnchor,setActiveAnchor]=useState('home');
 useEffect(()=>{const update=()=>{setScrolled(window.scrollY>30);if(page!=='home')return;let current='home';let nearestTop=-Infinity;for(const [anchor] of mobileLinks){const section=document.getElementById(anchor);if(!section)continue;const top=section.getBoundingClientRect().top;if(top<=150&&top>nearestTop){nearestTop=top;current=anchor}}setActiveAnchor(current)};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);window.addEventListener('hashchange',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update);window.removeEventListener('hashchange',update)}},[page]);
 return <header className={`site-header  ${scrolled?'scrolled':''}`}>
  <a href={sectionHref('home',page)} className="monogram" aria-label="Frederick and Veronica, home">F<span>&</span>V</a>
  <nav className="desktop-nav" aria-label="Main navigation">{links.map(([anchor,label])=><a key={anchor} href={sectionHref(anchor,page)} aria-current={page==='home'&&activeAnchor===anchor?'location':undefined}>{label}</a>)}</nav>
  <a className="header-cta" href={sectionHref('rsvp',page)} aria-current={page==='home'&&activeAnchor==='rsvp'?'location':undefined}>Kindly RSVP <ArrowUpRight size={16}/></a>
  <Dialog open={open} onOpenChange={setOpen}>
   <DialogTrigger asChild><button className="menu-button icon-button" aria-label="Open navigation"><Menu/></button></DialogTrigger>
   <DialogContent className={`mobile-menu ${page==='home'?'invitation-menu':''}`} showCloseButton={false}><DialogTitle className="sr-only">Navigation</DialogTitle><DialogDescription className="sr-only">Explore Frederick and Veronica’s wedding website.</DialogDescription><DialogClose className="menu-close icon-button" aria-label="Close navigation"><X/></DialogClose><span className="eyebrow">Frederick & Veronica</span>{mobileLinks.map(([anchor,label],i)=><a key={anchor} href={sectionHref(anchor,page)} aria-current={page==='home'&&activeAnchor===anchor?'location':undefined} onClick={()=>setOpen(false)}><span>0{i+1}</span>{label}</a>)}<p>A lifetime of us.</p></DialogContent>
  </Dialog>
 </header>
}
function Footer({page}:{page:string}){return <footer className="footer"><div className="footer-top"><a href={sectionHref('home',page)} className="footer-names">Frederick <i>&</i> Veronica</a><p>With love, always.</p></div><div className="footer-bottom"><span>FREDERICK AMOKOHENE & VERONICA OWUSU</span><div><a href={sectionHref('gallery',page)}>Photographs</a><a href={sectionHref('rsvp',page)}>RSVP</a><a href="/manage">Organizer</a><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Back to top ↑</button></div></div></footer>}
export function Frame({children,page}:{children:React.ReactNode,page:string}){return <div className={`wedding-site page-${page}`}><Header page={page}/><main id="main">{children}</main><Footer page={page}/><Toaster position="bottom-center" toastOptions={{style:{background:'#321821',color:'#fff8ef',border:'1px solid #795057'}}}/></div>}
export function Eyebrow({children}:{children:React.ReactNode}){return <span className="eyebrow">{children}</span>}
export function Photo({id,alt,className='',small=false}:{id:string,alt:string,className?:string,small?:boolean}){return <img src={src(id,small)} alt={alt} className={className} loading="lazy" width={1536} height={2048}/>}
export function Lightbox({index,setIndex,items=photos,initialPlaying=false}:{index:number|null,setIndex:(v:number|null)=>void,items?:typeof photos,initialPlaying?:boolean}){
 const [playing,setPlaying]=useState(initialPlaying);const touch=useRef<number|null>(null);const opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{setPlaying(initialPlaying)},[initialPlaying,index===null]);
 const move=(delta:number)=>setIndex(((index??0)+delta+items.length)%items.length);
 useEffect(()=>{if(index===null)return;const f=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft'){e.preventDefault();setIndex((index-1+items.length)%items.length)}if(e.key==='ArrowRight'){e.preventDefault();setIndex((index+1)%items.length)}};document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[index,items.length,setIndex]);
 useEffect(()=>{if(!playing||index===null)return;const t=setTimeout(()=>setIndex((index+1)%items.length),4500);return()=>clearTimeout(t)},[playing,index,items.length,setIndex]);
 const photo=index!==null?items[index]:null;
 return <Dialog open={index!==null} onOpenChange={o=>{if(!o){setIndex(null);setPlaying(false)}}}><DialogContent className="lightbox" showCloseButton={false} onOpenAutoFocus={()=>{opener.current=document.activeElement as HTMLElement}} onCloseAutoFocus={e=>{e.preventDefault();opener.current?.focus()}} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current!==null){const d=touch.current-e.changedTouches[0].clientX;if(Math.abs(d)>55)move(d>0?1:-1);touch.current=null}}}>
  <DialogTitle className="sr-only">{photo?.title??'Photograph'}</DialogTitle><DialogDescription className="sr-only">Use the left and right arrow keys, or swipe, to browse photographs.</DialogDescription>
  <div className="lightbox-top"><span>F <i>&</i> V <span className="lightbox-label">THE PHOTOGRAPHS</span></span><div><button className="icon-button" aria-label={playing?'Pause slideshow':'Play slideshow'} onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}</button>{photo&&<a className="icon-button" href={src(photo.id)} download={`${photo.id}.webp`} aria-label="Download this photograph"><Download/></a>}<DialogClose className="icon-button" aria-label="Close gallery"><X/></DialogClose></div></div>
  {photo&&<img key={photo.id} src={src(photo.id)} alt={photo.alt} className="lightbox-image"/>}
  <button className="lightbox-prev icon-button" aria-label="Previous photograph" onClick={()=>move(-1)}><ChevronLeft/></button><button className="lightbox-next icon-button" aria-label="Next photograph" onClick={()=>move(1)}><ChevronRight/></button>
  <div className="lightbox-bottom"><div><span className="eyebrow">{photo?.collection}</span><p>{photo?.title}</p></div><span>{String((index??0)+1).padStart(2,'0')} <span className="muted">/ {String(items.length).padStart(2,'0')}</span></span></div>
  {playing&&<div key={index} className="slide-progress"/>}
 </DialogContent></Dialog>
}
export function ShareButton(){const share=async()=>{try{const url=window.location.origin;if(navigator.share)await navigator.share({title:'Frederick & Veronica',text:'A lifetime of us. Celebrate Frederick and Veronica.',url});else{await navigator.clipboard.writeText(url);toast.success('Website link copied')}}catch(e){if((e as Error).name!=='AbortError')toast.error('Please copy the website address from your browser.')}};return <button className="text-link" onClick={share}>Share the celebration <Share2 size={15}/></button>}

export function Story(){return <Frame page="story"><section className="story-intro section-pad"><Eyebrow>THE TWO OF US</Eyebrow><h1>A thousand little moments.<br/><i>One beautiful us.</i></h1><p>Frederick Amokohene & Veronica Owusu</p></section><section className="story-spread"><div><Photo id="IMG_5390" alt={photos[3].alt}/></div><div className="story-spread-copy"><span className="story-number">01</span><Eyebrow>THE QUIET MOMENTS</Eyebrow><h2>Love is in<br/><i>the little things.</i></h2><p>A shared glance. A hand to hold. The comfort of simply being together. The moments that say everything, without saying a word.</p></div></section><section className="story-quote"><span>“</span><h2>Every love story is beautiful.<br/><i>Ours is our favourite.</i></h2><Eyebrow>FREDERICK & VERONICA</Eyebrow></section><section className="story-spread reverse"><div><Photo id="IMG_5090" alt={photos[5].alt}/></div><div className="story-spread-copy"><span className="story-number">02</span><Eyebrow>THE COLOURS OF US</Eyebrow><h2>A beautiful way<br/><i>to belong.</i></h2><p>Two people, side by side. A celebration of love, of family, and of all the things that make this chapter our own.</p><a className="text-link" href="/gallery?collection=Tradition">See our traditional portraits <ArrowUpRight size={17}/></a></div></section><section className="story-ending section-pad"><Eyebrow>AND SO, OUR NEXT CHAPTER</Eyebrow><h2>Here’s to everything<br/><i>still to come.</i></h2><a className="button button-burgundy" href="/celebration">Celebrate with us <ArrowUpRight size={17}/></a></section></Frame>}

export function Gallery({embedded=false}:{embedded?:boolean}={}){
 const [filter,setFilter]=useState('All photographs');const [index,setIndex]=useState<number|null>(null);const [slideshow,setSlideshow]=useState(false);const [saved,setSaved]=useState<string[]>([]);
 useEffect(()=>{const f=new URLSearchParams(window.location.search).get('collection');if(f==='Together'||f==='Tradition')setFilter(f);try{const v=JSON.parse(localStorage.getItem('fv-photo-favourites-v1')||'[]');if(Array.isArray(v))setSaved(v.filter(x=>typeof x==='string'&&photos.some(p=>p.id===x)))}catch{}},[]);
 const filtered=photos.filter(p=>filter==='All photographs'||(filter==='Favourites'?saved.includes(p.id):p.collection===filter));
 function favourite(id:string){setSaved(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];try{localStorage.setItem('fv-photo-favourites-v1',JSON.stringify(next))}catch{toast.error('Your browser cannot save favourites. They will last for this visit only.')}return next})}
 function open(i:number,play=false){setSlideshow(play);setIndex(i)}
 const Heading=embedded?'h2':'h1';
 const content=<><section className="gallery-heading section-pad"><div><Eyebrow>THE FOREVER COLLECTION</Eyebrow><Heading>Love, captured.<br/><i>Memories, kept.</i></Heading></div><div className="gallery-heading-aside"><p>Eight moments. A thousand feelings.</p><div className="gallery-main-actions"><button className="text-link" onClick={()=>{setFilter('All photographs');open(0,true)}}>Play the collection <Play size={17}/></button><a className="text-link" href="/Frederick-Veronica-Photographs.zip" download>Download all photos <Download size={17}/></a></div></div></section><section className="gallery-section"><div className="gallery-toolbar"><div className="filter-list" role="group" aria-label="Filter photographs">{['All photographs','Together','Tradition','Favourites'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>{setFilter(f);setIndex(null)}}>{f}{f==='Favourites'?` (${saved.length})`:''}</button>)}</div><span>{String(filtered.length).padStart(2,'0')} PHOTOGRAPHS</span></div>{filter==='Favourites'&&<p className="favourites-note">Your favourites are saved on this device.</p>}{filtered.length?<div className="gallery-grid">{filtered.map((p,i)=><article className="gallery-item" key={p.id}><button className="gallery-card" onClick={()=>open(i)} aria-label={`View ${p.title}`}><div className="gallery-card-image"><Photo id={p.id} alt={p.alt} small/><span className="photo-expand"><ArrowUpRight/></span></div></button><div className="gallery-caption-row"><span>{p.title}</span><button className={`favourite-button icon-button ${saved.includes(p.id)?'is-saved':''}`} onClick={()=>favourite(p.id)} aria-label={`${saved.includes(p.id)?'Unsave':'Save'} ${p.title}`} aria-pressed={saved.includes(p.id)}><Heart size={20}/></button></div></article>)}</div>:<div className="gallery-empty"><Heart size={30}/><h2>A place for your favourites.</h2><p>Tap the heart beside any photograph to keep it here.</p><button className="text-link" onClick={()=>setFilter('All photographs')}>Browse all photographs <ArrowRight size={17}/></button></div>}<div className="gallery-outro"><span>Every photograph, a little piece of forever.</span><ShareButton/></div></section><Lightbox index={index} setIndex={setIndex} items={filtered} initialPlaying={slideshow}/></>;
 return embedded?content:<Frame page="gallery">{content}</Frame>;
}

export function Guestbook({embedded=false}:{embedded?:boolean}={}){
 const [sending,setSending]=useState(false);const [sent,setSent]=useState(false);const [name,setName]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const requestId=useRef<string>('');
 useEffect(()=>{
 const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;const lifecycle=new AbortController();
 try{void Promise.resolve(context.registerTool({name:'draft_wedding_wish',title:'Draft a wedding wish',description:'Fill in the visible guestbook form for Frederick and Veronica. This stages a draft only; it does not send or save the message.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:2,maxLength:80},message:{type:'string',minLength:10,maxLength:1500}},required:['name','message'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const v=input as {name?:unknown,message?:unknown};if(!v||typeof v.name!=='string'||typeof v.message!=='string'||v.name.trim().length<2||v.name.trim().length>80||v.message.trim().length<10||v.message.trim().length>1500)throw new Error('A name of 2–80 characters and a message of 10–1,500 characters are required.');setName(v.name.trim());setMessage(v.message.trim());setSent(false);setError('');requestId.current='';return {status:'drafted',saved:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setSending(true);try{if(!requestId.current){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');requestId.current=[h.slice(0,8),h.slice(8,12),h.slice(12,16),h.slice(16,20),h.slice(20)].join('-')}const r=await fetch('/api/wishes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,message,id:requestId.current,website:(new FormData(e.currentTarget)).get('website')})});const body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error||'Your message could not be sent. Please try again.');setSent(true)}catch(e){setError((e as Error).message)}finally{setSending(false)}}
 const Heading=embedded?'h2':'h1';
 const content=<><section className="guestbook-layout"><div className="guestbook-photo"><Photo id="IMG_5132" alt={photos[6].alt}/><div/><span>LOVE, IN EVERY WORD.</span></div><div className="guestbook-panel"><Eyebrow>A KEEPSAKE OF YOUR KIND WORDS</Eyebrow><Heading>A little note.<br/><i>A lot of love.</i></Heading><p>A wish, a memory, a piece of advice for the years ahead. Leave something for Frederick and Veronica to treasure.</p>{sent?<div className="wish-success" role="status"><span><Check size={30}/></span><h2>We’ll treasure<br/><i>your words.</i></h2><p>Thank you, {name}. Your message has been saved for Frederick and Veronica.</p><a className="text-link" href={embedded?'#gallery':'/gallery'}>Stay a little longer <ArrowUpRight size={17}/></a></div>:<form method="post" action="/api/wishes" onSubmit={submit} className="wish-form"><div className="field"><label htmlFor="wish-name">Your name</label><input id="wish-name" name="name" disabled={sending} value={name} onChange={e=>{setName(e.target.value);requestId.current=''}} placeholder="The name they know you by" required minLength={2} maxLength={80} autoComplete="name"/></div><div className="field"><label htmlFor="wish-message">Your message to the couple</label><textarea id="wish-message" name="message" disabled={sending} value={message} onChange={e=>{setMessage(e.target.value);requestId.current=''}} placeholder="Wishing you a lifetime of…" required minLength={10} maxLength={1500} rows={5}/><span className="character-count">{message.length} / 1,500</span></div><div className="honey" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><p className="privacy-note">Your message will be saved privately in the wedding guestbook.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="button button-burgundy" disabled={sending}>{sending?<><LoaderCircle className="spin" size={17}/>Sending your wish…</>:<>Send with love <Heart size={17}/></>}</button></form>}</div></section></>;
 return embedded?content:<Frame page="guestbook">{content}</Frame>;
}
